version: '3.8'
services:
  postgres-devoteam:
    platform: linux/amd64
    image: postgres:14.2
    ports:
      - 5438:5432
    env_file:
      - docker/postgres/.env
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
    init: true
  api-devoteam:
    build: ./
    image: devoteam
    command: bash -c "go run app/main.go"
    volumes:
      - ./:/usr/src/app
    depends_on:
      - postgres-devoteam
    ports:
      - 50052:50052
      - 8090:8090
    init: true
    env_file:
      - docker/api/.env

networks:
  default:
    name: devoteam_default
